import type { SubjectId } from '@/engine/types';

/**
 * Chapter structure of every NET subject (based on the HSSC/FSc Part I & II syllabi
 * that the NET is drawn from). Chapter ids are the contract between the question
 * bank (`src/bank/<subject>/<chapter-id>.ts`) and paper assembly.
 *
 * `weight` is the chapter's relative share of questions in a generated paper. It
 * reflects how often each chapter appears in reported NET papers (see
 * docs/EXAM_PATTERN.md); a paper draws chapter counts proportionally, with a
 * little per-paper jitter, so no two papers have the identical distribution.
 */
export interface ChapterInfo {
  id: string;
  name: string;
  /** FSc part the chapter belongs to (`XI` = Part I, `XII` = Part II). */
  part: 'XI' | 'XII' | '-';
  weight: number;
  /** Key sub-topics, used by authors and the bank browser. */
  topics: readonly string[];
}

export interface SubjectInfo {
  id: SubjectId;
  name: string;
  chapters: readonly ChapterInfo[];
}

const ch = (
  id: string,
  name: string,
  part: ChapterInfo['part'],
  weight: number,
  topics: readonly string[],
): ChapterInfo => ({
  id,
  name,
  part,
  weight,
  topics,
});

export const SYLLABUS: Readonly<Record<SubjectId, SubjectInfo>> = {
  mathematics: {
    id: 'mathematics',
    name: 'Mathematics',
    // Weights follow chapter counts reported from 2024-25 NET sittings (trigonometry ~18%,
    // conics ~9%, sequences/probability ~7% each): see docs/EXAM_PATTERN.md.
    chapters: [
      ch('number-systems', 'Number Systems & Complex Numbers', 'XI', 5, [
        'real number properties',
        'complex numbers',
        'modulus and argument',
        'conjugates',
        'polar form',
      ]),
      ch('sets-functions-groups', 'Sets, Functions and Groups', 'XI', 3, [
        'set operations',
        'Venn diagrams',
        'relations and functions',
        'binary operations',
        'groups',
        'logic',
      ]),
      ch('matrices-determinants', 'Matrices and Determinants', 'XI', 4, [
        'matrix algebra',
        'determinants',
        'properties of determinants',
        'inverse',
        'rank',
        'systems of linear equations',
        'Cramer rule',
      ]),
      ch('quadratic-equations', 'Quadratic Equations', 'XI', 3, [
        'roots and discriminant',
        'sum and product of roots',
        'nature of roots',
        'cube roots of unity',
        'equations reducible to quadratic',
        'remainder and factor theorem',
      ]),
      ch('partial-fractions', 'Partial Fractions', 'XI', 2, [
        'linear factors',
        'repeated factors',
        'quadratic factors',
        'improper fractions',
      ]),
      ch('sequences-series', 'Sequences and Series', 'XI', 7, [
        'arithmetic progression',
        'geometric progression',
        'harmonic progression',
        'means',
        'infinite geometric series',
        'sum of series',
      ]),
      ch(
        'permutation-combination-probability',
        'Permutation, Combination and Probability',
        'XI',
        7,
        [
          'factorial',
          'permutations',
          'circular permutations',
          'combinations',
          'probability',
          'addition and multiplication laws',
        ],
      ),
      ch('induction-binomial', 'Mathematical Induction and Binomial Theorem', 'XI', 3, [
        'mathematical induction',
        'binomial expansion',
        'general term',
        'middle term',
        'term independent of x',
        'binomial series',
      ]),
      ch('trigonometry-fundamentals', 'Fundamentals of Trigonometry', 'XI', 3, [
        'angle measure',
        'radians and degrees',
        'arc length and sector area',
        'trigonometric ratios',
        'signs in quadrants',
      ]),
      ch('trigonometric-identities', 'Trigonometric Identities', 'XI', 3.5, [
        'compound angles',
        'double and half angles',
        'sum-product formulas',
        'allied angles',
      ]),
      ch('trigonometric-graphs', 'Trigonometric Functions and their Graphs', 'XI', 2.5, [
        'domain and range',
        'period',
        'graphs',
        'maximum and minimum values',
      ]),
      ch('trigonometry-applications', 'Application of Trigonometry', 'XI', 4.5, [
        'solution of triangles',
        'law of sines',
        'law of cosines',
        'area of triangle',
        'circum-radius and in-radius',
        'heights and distances',
      ]),
      ch('inverse-trigonometry', 'Inverse Trigonometric Functions', 'XI', 2, [
        'principal values',
        'domains and ranges',
        'inverse identities',
      ]),
      ch('trigonometric-equations', 'Solutions of Trigonometric Equations', 'XI', 2.5, [
        'general solutions',
        'solutions in an interval',
      ]),
      ch('functions-limits', 'Functions and Limits', 'XII', 6, [
        'domain and range',
        'composite and inverse functions',
        'even and odd functions',
        'limits',
        'standard limits',
        'continuity',
      ]),
      ch('differentiation', 'Differentiation', 'XII', 7, [
        'derivative rules',
        'chain rule',
        'implicit differentiation',
        'trigonometric and inverse derivatives',
        'exponential and logarithmic derivatives',
        'higher derivatives',
        'tangents and normals',
        'maxima and minima',
        'Maclaurin series',
      ]),
      ch('integration', 'Integration', 'XII', 7, [
        'antiderivatives',
        'substitution',
        'integration by parts',
        'partial fractions in integration',
        'definite integrals',
        'area under curves',
        'differential equations',
      ]),
      ch('analytic-geometry', 'Introduction to Analytic Geometry', 'XII', 6, [
        'distance and section formula',
        'slope',
        'equations of lines',
        'angle between lines',
        'distance from a point to a line',
        'concurrency',
        'pair of lines',
      ]),
      ch('linear-programming', 'Linear Inequalities and Linear Programming', 'XII', 2, [
        'linear inequalities',
        'feasible region',
        'corner points',
        'optimal solution',
      ]),
      ch('conic-sections', 'Conic Sections', 'XII', 9, [
        'circle',
        'tangents to circles',
        'parabola',
        'ellipse',
        'hyperbola',
        'eccentricity',
        'focus and directrix',
      ]),
      ch('vectors', 'Vectors', 'XII', 6, [
        'vector algebra',
        'unit vectors',
        'dot product',
        'cross product',
        'projection',
        'area and volume',
        'scalar triple product',
      ]),
    ],
  },
  physics: {
    id: 'physics',
    name: 'Physics',
    // Reports from 2022-25 sittings: units/dimensions, YDSE, SHM and modern/nuclear physics
    // recur in nearly every paper; Part I and Part II are roughly balanced.
    chapters: [
      ch('measurements', 'Measurements', 'XI', 4.5, [
        'SI units',
        'prefixes',
        'errors and uncertainties',
        'significant figures',
        'dimensions',
        'dimensional analysis',
      ]),
      ch('vectors-equilibrium', 'Vectors and Equilibrium', 'XI', 4, [
        'vector addition',
        'resolution',
        'dot and cross product',
        'torque',
        'equilibrium conditions',
      ]),
      ch('motion-force', 'Motion and Force', 'XI', 5.5, [
        'kinematics',
        'equations of motion',
        'Newton laws',
        'momentum and impulse',
        'collisions',
        'projectile motion',
      ]),
      ch('work-energy', 'Work and Energy', 'XI', 5, [
        'work',
        'power',
        'kinetic and potential energy',
        'work-energy theorem',
        'conservation of energy',
        'escape velocity',
      ]),
      ch('circular-motion', 'Circular Motion', 'XI', 5, [
        'angular quantities',
        'centripetal force',
        'moment of inertia',
        'angular momentum',
        'rotational kinetic energy',
        'satellites',
        'artificial gravity',
      ]),
      ch('fluid-dynamics', 'Fluid Dynamics', 'XI', 3, [
        'viscosity',
        'Stokes law',
        'terminal velocity',
        'equation of continuity',
        'Bernoulli equation',
      ]),
      ch('oscillations', 'Oscillations', 'XI', 5, [
        'simple harmonic motion',
        'mass-spring system',
        'simple pendulum',
        'energy in SHM',
        'resonance',
        'damping',
      ]),
      ch('waves', 'Waves', 'XI', 5, [
        'wave speed',
        'speed of sound',
        'superposition',
        'stationary waves',
        'beats',
        'Doppler effect',
        'strings and pipes',
      ]),
      ch('physical-optics', 'Physical Optics', 'XI', 5, [
        'interference',
        'Young double slit',
        'thin films',
        'Newton rings',
        'diffraction grating',
        'polarization',
      ]),
      ch('optical-instruments', 'Optical Instruments', 'XI', 3, [
        'magnification',
        'microscopes',
        'telescopes',
        'resolving power',
        'optical fibres',
      ]),
      ch('thermodynamics', 'Heat and Thermodynamics', 'XI', 5, [
        'kinetic theory',
        'gas laws',
        'first law',
        'molar specific heats',
        'heat engines',
        'Carnot cycle',
        'entropy',
      ]),
      ch('electrostatics', 'Electrostatics', 'XII', 6, [
        'Coulomb law',
        'electric field',
        'electric flux',
        'Gauss law',
        'potential',
        'capacitors',
        'dielectrics',
      ]),
      ch('current-electricity', 'Current Electricity', 'XII', 6, [
        'Ohm law',
        'resistivity',
        'series and parallel',
        'power',
        'EMF and internal resistance',
        'Kirchhoff rules',
        'Wheatstone bridge',
        'potentiometer',
      ]),
      ch('electromagnetism', 'Electromagnetism', 'XII', 5.5, [
        'magnetic force',
        'Ampere law',
        'solenoid',
        'charged particles in fields',
        'e/m',
        'galvanometer, ammeter, voltmeter',
      ]),
      ch('em-induction', 'Electromagnetic Induction', 'XII', 4, [
        'Faraday law',
        'Lenz law',
        'motional EMF',
        'self and mutual induction',
        'generators',
        'transformers',
      ]),
      ch('alternating-current', 'Alternating Current', 'XII', 4, [
        'rms values',
        'reactance',
        'impedance',
        'RLC circuits',
        'resonance',
        'power factor',
      ]),
      ch('solids', 'Physics of Solids', 'XII', 2, [
        'crystal types',
        'stress and strain',
        'elastic moduli',
        'band theory',
        'superconductors',
        'magnetism of materials',
      ]),
      ch('electronics', 'Electronics', 'XII', 3, [
        'semiconductors',
        'p-n junction',
        'rectification',
        'transistors',
        'logic gates',
        'op-amps',
      ]),
      ch('modern-physics', 'Dawn of Modern Physics', 'XII', 6, [
        'relativity',
        'black-body radiation',
        'photoelectric effect',
        'Compton effect',
        'pair production',
        'de Broglie waves',
        'uncertainty principle',
      ]),
      ch('atomic-spectra', 'Atomic Spectra', 'XII', 3.5, [
        'Bohr model',
        'hydrogen spectrum',
        'X-rays',
        'lasers',
      ]),
      ch('nuclear-physics', 'Nuclear Physics', 'XII', 5, [
        'nuclear composition',
        'mass defect and binding energy',
        'radioactivity',
        'half-life',
        'fission and fusion',
        'radiation detectors',
        'elementary particles',
      ]),
    ],
  },
  chemistry: {
    id: 'chemistry',
    name: 'Chemistry',
    // Candidates report NET chemistry as roughly 50-60% organic, 25-30% physical and
    // 15-20% inorganic/industrial/environmental, mostly textbook-statement recall.
    chapters: [
      ch('basic-concepts', 'Basic Concepts', 'XI', 3, [
        'moles',
        'Avogadro number',
        'empirical and molecular formula',
        'stoichiometry',
        'limiting reactant',
        'yield',
      ]),
      ch('experimental-techniques', 'Experimental Techniques in Chemistry', 'XI', 1, [
        'filtration',
        'crystallization',
        'sublimation',
        'solvent extraction',
        'chromatography',
      ]),
      ch('gases', 'Gases', 'XI', 2, [
        'gas laws',
        'ideal gas equation',
        'Dalton law',
        'Graham law',
        'kinetic theory',
        'non-ideal behaviour',
        'plasma',
      ]),
      ch('liquids-solids', 'Liquids and Solids', 'XI', 1.5, [
        'intermolecular forces',
        'hydrogen bonding',
        'vapour pressure',
        'crystal lattices',
        'types of solids',
      ]),
      ch('atomic-structure', 'Atomic Structure', 'XI', 2.5, [
        'subatomic particles',
        'Bohr model',
        'quantum numbers',
        'orbitals',
        'electronic configuration',
        'spectra',
      ]),
      ch('chemical-bonding', 'Chemical Bonding', 'XI', 3, [
        'ionic and covalent bonds',
        'VSEPR',
        'hybridization',
        'molecular orbital theory',
        'bond energy',
        'dipole moment',
      ]),
      ch('thermochemistry', 'Thermochemistry', 'XI', 1.5, [
        'enthalpy',
        'Hess law',
        'Born-Haber cycle',
        'calorimetry',
      ]),
      ch('chemical-equilibrium', 'Chemical Equilibrium', 'XI', 2, [
        'Kc and Kp',
        'Le Chatelier principle',
        'pH and pOH',
        'buffers',
        'solubility product',
        'common ion effect',
      ]),
      ch('solutions', 'Solutions', 'XI', 1.5, [
        'concentration units',
        'Raoult law',
        'colligative properties',
        'hydration and hydrolysis',
      ]),
      ch('electrochemistry', 'Electrochemistry', 'XI', 2, [
        'oxidation numbers',
        'balancing redox',
        'electrolysis',
        'electrode potentials',
        'cells and batteries',
      ]),
      ch('reaction-kinetics', 'Reaction Kinetics', 'XI', 1.5, [
        'rate of reaction',
        'order',
        'half-life',
        'activation energy',
        'catalysis',
      ]),
      ch('periodicity', 'Periodic Classification and Periodicity', 'XII', 2.5, [
        'periodic table',
        'atomic radius',
        'ionization energy',
        'electron affinity',
        'electronegativity',
      ]),
      ch('s-block', 's-Block Elements', 'XII', 1.5, [
        'alkali metals',
        'alkaline earth metals',
        'diagonal relationship',
        'compounds and uses',
      ]),
      ch('p-block', 'p-Block Elements (Groups IIIA to VIIIA)', 'XII', 2.5, [
        'boron and aluminium',
        'carbon and silicon',
        'nitrogen and phosphorus',
        'oxygen and sulphur',
        'halogens',
        'noble gases',
      ]),
      ch('transition-elements', 'Transition Elements', 'XII', 1.5, [
        'properties',
        'complex compounds',
        'iron and steel',
        'chromate and permanganate',
      ]),
      ch('organic-fundamentals', 'Fundamental Principles of Organic Chemistry', 'XII', 5, [
        'classification',
        'functional groups',
        'isomerism',
        'hybridization in carbon',
      ]),
      ch('hydrocarbons', 'Hydrocarbons (Aliphatic and Aromatic)', 'XII', 9, [
        'alkanes',
        'alkenes',
        'alkynes',
        'benzene',
        'electrophilic substitution',
        'reactions and mechanisms',
      ]),
      ch('alkyl-halides-amines', 'Alkyl Halides and Amines', 'XII', 4, [
        'SN1 and SN2',
        'elimination',
        'Grignard reagent',
        'amines',
      ]),
      ch('alcohols-phenols-ethers', 'Alcohols, Phenols and Ethers', 'XII', 5, [
        'classification',
        'preparation',
        'reactions',
        'acidity of phenol',
        'tests',
      ]),
      ch('carbonyl-compounds', 'Aldehydes and Ketones', 'XII', 5, [
        'preparation',
        'nucleophilic addition',
        'oxidation and reduction',
        'identification tests',
      ]),
      ch('carboxylic-acids', 'Carboxylic Acids and Derivatives', 'XII', 4, [
        'acidity',
        'preparation',
        'derivatives',
        'amino acids',
      ]),
      ch('macromolecules', 'Biochemistry and Macromolecules', 'XII', 3, [
        'polymers',
        'carbohydrates',
        'proteins',
        'lipids',
        'enzymes',
        'nucleic acids',
      ]),
      ch('industrial-environmental', 'Industrial and Environmental Chemistry', 'XII', 3, [
        'fertilizers',
        'cement',
        'paper',
        'petroleum',
        'pollution',
        'ozone',
        'water treatment',
      ]),
    ],
  },
  computer: {
    id: 'computer',
    name: 'Computer Science',
    chapters: [
      ch('computer-basics', 'Basics of Information Technology', 'XI', 3, [
        'IT terms',
        'types of computers',
        'hardware and software',
        'input and output devices',
        'storage',
      ]),
      ch('computer-architecture', 'Computer Architecture', 'XI', 3, [
        'CPU',
        'registers',
        'buses',
        'instruction cycle',
        'memory hierarchy',
      ]),
      ch('number-systems', 'Number Systems and Data Representation', 'XI', 4, [
        'binary',
        'octal',
        'hexadecimal',
        'conversions',
        'binary arithmetic',
        'complements',
        'codes',
      ]),
      ch('networks-communication', 'Data Communication and Networks', 'XI', 4, [
        'transmission modes',
        'media',
        'topologies',
        'network types',
        'OSI model',
        'protocols',
        'internet',
      ]),
      ch('security-ethics', 'Security, Copyright and the Law', 'XI', 2, [
        'viruses and malware',
        'security measures',
        'privacy',
        'copyright',
        'cybercrime',
      ]),
      ch('operating-systems', 'Operating Systems and Applications', 'XI', 2, [
        'OS functions',
        'Windows',
        'word processing',
        'spreadsheets',
        'email and browsing',
      ]),
      ch('databases', 'Databases', 'XII', 4, [
        'data and information',
        'DBMS concepts',
        'keys',
        'relationships',
        'ER modelling',
        'normalization',
        'MS Access',
      ]),
      ch('c-basics', 'C Programming: Basics and I/O', 'XII', 4, [
        'program structure',
        'data types',
        'variables and constants',
        'operators',
        'printf and scanf',
        'escape sequences',
      ]),
      ch('c-control', 'C Programming: Decisions and Loops', 'XII', 5, [
        'if-else',
        'switch',
        'for',
        'while',
        'do-while',
        'break and continue',
        'nested loops',
      ]),
      ch('c-functions-files', 'C Programming: Functions, Arrays and Files', 'XII', 3, [
        'functions',
        'scope',
        'arrays',
        'strings',
        'file handling',
      ]),
      ch('logic-algorithms', 'Logic Gates and Problem Solving', '-', 3, [
        'Boolean algebra',
        'logic gates',
        'truth tables',
        'algorithms',
        'flowcharts',
      ]),
    ],
  },
  english: {
    id: 'english',
    name: 'English',
    // NUST: "The paper of English is on the pattern of SAT exam." Weights follow the
    // item mix reported for NET English (vocabulary > comprehension > completion > rest).
    chapters: [
      ch('vocabulary', 'Vocabulary: Synonyms and Antonyms', '-', 14, [
        'synonyms',
        'antonyms',
        'word meaning',
        'antonym phrases',
      ]),
      ch('sentence-completion', 'Sentence Completion', '-', 8, [
        'single blank',
        'double blank',
        'vocabulary in context',
        'logical connectors',
      ]),
      ch('comprehension', 'Reading Comprehension', '-', 9, [
        'main idea',
        'inference',
        'reference',
        'vocabulary in context',
        'tone and purpose',
      ]),
      ch('analogies', 'Analogies', '-', 5, ['word relationships', 'SAT-style pairs']),
      ch('grammar', 'Grammar and Sentence Correction', '-', 5, [
        'tenses',
        'subject-verb agreement',
        'prepositions',
        'articles',
        'pronouns',
        'modifiers',
        'parallelism',
        'sentence correction',
      ]),
      ch('spelling', 'Spelling', '-', 2, ['correctly spelt word', 'misspelt word']),
    ],
  },
  biology: {
    id: 'biology',
    name: 'Biology',
    chapters: [
      ch('biological-molecules', 'Biological Molecules and Enzymes', 'XI', 4, [
        'carbohydrates',
        'proteins',
        'lipids',
        'nucleic acids',
        'enzymes',
        'enzyme inhibition',
      ]),
      ch('cell-biology', 'The Cell', 'XI', 4, [
        'cell theory',
        'organelles',
        'membranes',
        'prokaryotic and eukaryotic cells',
      ]),
      ch('diversity-of-life', 'Variety of Life (Viruses to Animals)', 'XI', 4, [
        'classification',
        'viruses',
        'bacteria',
        'protists',
        'fungi',
        'plant kingdom',
        'animal kingdom',
      ]),
      ch('bioenergetics', 'Bioenergetics', 'XI', 3, ['photosynthesis', 'respiration', 'ATP']),
      ch('nutrition-gas-exchange', 'Nutrition and Gaseous Exchange', 'XI', 3, [
        'human digestion',
        'plant nutrition',
        'respiratory system',
      ]),
      ch('transport', 'Transport', 'XI', 3, [
        'transport in plants',
        'heart and blood vessels',
        'blood',
        'lymphatic system',
        'immunity',
      ]),
      ch('homeostasis', 'Homeostasis', 'XII', 3, [
        'osmoregulation',
        'excretion',
        'kidney',
        'thermoregulation',
      ]),
      ch('support-movement', 'Support and Movement', 'XII', 2, [
        'skeleton',
        'joints',
        'muscles',
        'plant support',
      ]),
      ch('coordination-control', 'Coordination and Control', 'XII', 4, [
        'nervous system',
        'neurons',
        'hormones',
        'plant hormones',
        'behaviour',
      ]),
      ch('reproduction-development', 'Reproduction, Growth and Development', 'XII', 3, [
        'reproduction in plants and animals',
        'human reproduction',
        'development',
        'ageing',
      ]),
      ch('genetics', 'Chromosomes, Cell Cycle and Genetics', 'XII', 5, [
        'DNA structure and replication',
        'protein synthesis',
        'mitosis and meiosis',
        'Mendelian genetics',
        'linkage',
        'sex determination',
      ]),
      ch('biotechnology-evolution', 'Biotechnology and Evolution', 'XII', 3, [
        'recombinant DNA',
        'PCR',
        'cloning',
        'evolution theories',
        'Hardy-Weinberg',
      ]),
      ch('ecology', 'Ecosystems and Environment', 'XII', 3, [
        'ecosystem',
        'food chains',
        'biogeochemical cycles',
        'biomes',
        'pollution',
      ]),
    ],
  },
  quantitative: {
    id: 'quantitative',
    name: 'Quantitative Mathematics',
    chapters: [
      ch('arithmetic', 'Arithmetic and Number Properties', '-', 5, [
        'fractions and decimals',
        'HCF and LCM',
        'divisibility',
        'exponents and surds',
        'number properties',
      ]),
      ch('percentages-ratios', 'Percentages, Ratios and Averages', '-', 5, [
        'percentages',
        'profit and loss',
        'simple and compound interest',
        'ratio and proportion',
        'mixtures',
        'averages',
      ]),
      ch('algebra', 'Algebra, Functions and Matrices', '-', 6, [
        'linear and simultaneous equations',
        'quadratic equations',
        'inequalities',
        'functions',
        'sequences',
        'matrices basics',
      ]),
      ch('word-problems', 'Word Problems', '-', 5, [
        'time and work',
        'speed, distance and time',
        'ages',
        'consecutive numbers',
        'pipes and cisterns',
      ]),
      ch('geometry', 'Geometry, Mensuration and Trigonometry', '-', 5, [
        'angles and lines',
        'triangles',
        'circles',
        'areas and volumes',
        'coordinate geometry',
        'heights and distances',
      ]),
      ch('statistics-data', 'Statistics, Counting and Data Interpretation', '-', 4, [
        'mean, median and mode',
        'tables and charts',
        'probability',
        'permutations and combinations',
      ]),
    ],
  },
  design: {
    id: 'design',
    name: 'Design Aptitude',
    // Areas from NUST SADA's "Design Aptitude NET guidelines".
    chapters: [
      ch('design-fundamentals', 'Design Fundamentals and Theory', '-', 6, [
        'elements of design',
        'principles of design',
        'Gestalt principles',
        'ratio and proportion systems',
        'colour theory',
        'patterns in nature',
        'visual composition',
      ]),
      ch('visual-arts', 'Visual Arts and Techniques', '-', 4, [
        'drawing and painting',
        'perspective',
        'shapes and geometry',
        'human proportions',
        'form-making',
        'material properties',
      ]),
      ch('design-history', 'Design History and Context', '-', 5, [
        'iconic artists and designers',
        'design movements',
        'local crafts',
        'Islamic art and architecture',
        'man and environment',
      ]),
      ch('visual-reasoning', 'Problem Solving and Visual Communication', '-', 6, [
        'non-verbal reasoning',
        'figure series',
        'mirror and water images',
        'rotation',
        'paper folding',
        'cube nets',
        'symbols and signage',
      ]),
      ch('contemporary-practice', 'Contemporary and Emerging Practices', '-', 3, [
        'design process',
        'studio culture',
        'local artists and architects',
        'emerging materials and technologies',
        'sustainability',
      ]),
    ],
  },
  intelligence: {
    id: 'intelligence',
    name: 'Intelligence / Analytical Reasoning',
    chapters: [
      ch('series', 'Number and Letter Series', '-', 5, [
        'number series',
        'letter series',
        'missing terms',
      ]),
      ch('coding-decoding', 'Coding and Decoding', '-', 3, ['letter coding', 'number coding']),
      ch('relations-directions', 'Blood Relations and Directions', '-', 3, [
        'family relations',
        'direction sense',
      ]),
      ch('logical-reasoning', 'Logical and Analytical Reasoning', '-', 5, [
        'syllogisms',
        'arrangements',
        'statements and conclusions',
        'odd one out',
        'analogies',
      ]),
    ],
  },
};

/**
 * Share of parametric (randomised-value) questions per subject at the default hybrid
 * setting. Calibrated to how computational each NET section is: maths is largely
 * calculation, physics mostly conceptual with 10-20% numericals plus scaling items,
 * chemistry and biology mostly textbook recall. The paper-level hybrid slider scales
 * these values proportionally.
 */
export const SUBJECT_DYNAMIC_SHARE: Readonly<Record<SubjectId, number>> = {
  mathematics: 0.6,
  physics: 0.35,
  chemistry: 0.25,
  computer: 0.35,
  english: 0.5,
  biology: 0.2,
  quantitative: 0.75,
  design: 0.4,
  intelligence: 0.75,
};

/** Default chapter weights for a subject, as used by paper blueprints. */
export function defaultChapterWeights(subject: SubjectId): Record<string, number> {
  return Object.fromEntries(SYLLABUS[subject].chapters.map((c) => [c.id, c.weight]));
}

export function chapterName(subject: SubjectId, chapterId: string): string {
  return SYLLABUS[subject].chapters.find((c) => c.id === chapterId)?.name ?? chapterId;
}
