/**
 * Summarises the question bank: templates per subject/chapter, kinds, origins and
 * difficulty. Writes docs/BANK.md and prints a compact table.
 *
 *   npm run bank:report
 */
import { writeFileSync } from 'node:fs';
import { SYLLABUS } from '../src/config/syllabus';
import { loadBankModules } from '../src/engine/registry';
import { SUBJECT_IDS, type QuestionTemplate } from '../src/engine/types';

const modules = await loadBankModules();
const all = modules.flatMap((m) => m.module.templates);

interface Row {
  chapter: string;
  name: string;
  total: number;
  dynamic: number;
  fixed: number;
  sets: number;
  pastPaper: number;
  d: [number, number, number];
}

function rowFor(name: string, chapter: string, templates: QuestionTemplate[]): Row {
  return {
    chapter,
    name,
    total: templates.length,
    dynamic: templates.filter((t) => t.kind === 'dynamic').length,
    fixed: templates.filter((t) => t.kind === 'static').length,
    sets: templates.filter((t) => t.kind === 'set').length,
    pastPaper: templates.filter((t) => t.origin === 'past-paper').length,
    d: [1, 2, 3].map((d) => templates.filter((t) => t.difficulty === d).length) as [
      number,
      number,
      number,
    ],
  };
}

const lines: string[] = [
  '# Question bank report',
  '',
  '_Generated by `npm run bank:report`. Counts are templates; every dynamic template produces',
  'a fresh variant (new values, new distractors) each time it is used._',
  '',
  `**Total templates:** ${all.length} — dynamic ${all.filter((t) => t.kind === 'dynamic').length}, ` +
    `fixed ${all.filter((t) => t.kind === 'static').length}, passage sets ${all.filter((t) => t.kind === 'set').length}; ` +
    `past-paper style ${all.filter((t) => t.origin === 'past-paper').length}.`,
  '',
];

for (const subject of SUBJECT_IDS) {
  const info = SYLLABUS[subject];
  const subjectTemplates = all.filter((t) => t.subject === subject);
  if (!subjectTemplates.length) continue;
  lines.push(`## ${info.name} (${subjectTemplates.length})`, '');
  lines.push('| Chapter | Templates | Dynamic | Fixed | Sets | Past-paper | Easy / Med / Hard |');
  lines.push('| --- | ---: | ---: | ---: | ---: | ---: | :---: |');
  for (const ch of info.chapters) {
    const row = rowFor(
      ch.name,
      ch.id,
      subjectTemplates.filter((t) => t.chapter === ch.id),
    );
    lines.push(
      `| ${row.name} | ${row.total} | ${row.dynamic} | ${row.fixed} | ${row.sets} | ${row.pastPaper} | ${row.d.join(' / ')} |`,
    );
  }
  lines.push('');
}

writeFileSync(new URL('../docs/BANK.md', import.meta.url), `${lines.join('\n')}\n`);

const table = SUBJECT_IDS.map((s) => {
  const ts = all.filter((t) => t.subject === s);
  const empty = SYLLABUS[s].chapters
    .filter((c) => !ts.some((t) => t.chapter === c.id))
    .map((c) => c.id);
  return {
    subject: s,
    templates: ts.length,
    parametric: ts.filter((t) => t.kind !== 'static').length,
    chapters: SYLLABUS[s].chapters.length,
    emptyChapters: empty.length,
  };
});
console.table(table);
console.log(`Total: ${all.length} templates. Wrote docs/BANK.md`);
