/**
 * Command-line Full Length Paper generator.
 *
 *   npm run paper -- --type engineering                 # random paper, Markdown to stdout
 *   npm run paper -- --code ENG-K7Q2-9XM4 --out paper.md # regenerate a shared paper
 *   npm run paper -- --type business --seed ABCD1234 --format json --out paper.json
 *   npm run paper -- --type engineering --solutions      # include worked solutions
 *
 * Markdown output keeps $...$ LaTeX, which GitHub renders natively.
 */
import { writeFileSync } from 'node:fs';
import { EXAM_TYPES, examTypeByCode, examTypeById } from '../src/config/exams';
import { chapterName } from '../src/config/syllabus';
import { normalizeSeed, randomSeed } from '../src/engine/rng';
import type { Paper } from '../src/engine/types';
import { BANK_VERSION, generatePaper, resolvePaperCode } from '../src/exam/papers';

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
const flag = (name: string) => process.argv.includes(`--${name}`);

if (flag('help')) {
  console.log(`Usage: npm run paper -- [--type <id|CODE>] [--seed <seed>] [--code <paper code>] [--format md|json] [--solutions] [--out <file>]
Exam types: ${EXAM_TYPES.map((e) => `${e.id} (${e.code})`).join(', ')}`);
  process.exit(0);
}

let examType = arg('type') ?? 'engineering';
let seed = arg('seed') ? normalizeSeed(arg('seed') as string) : randomSeed();
const code = arg('code');
if (code) {
  const resolved = resolvePaperCode(code);
  if (!resolved) {
    console.error(`Invalid paper code "${code}"`);
    process.exit(1);
  }
  examType = resolved.examType;
  seed = resolved.seed;
}
const exam = examTypeById(examType) ?? examTypeByCode(examType);
if (!exam) {
  console.error(`Unknown exam type "${examType}". Use --help for the list.`);
  process.exit(1);
}

const paper = await generatePaper({ examType: exam.id, seed });
const format = arg('format') ?? (arg('out')?.endsWith('.json') ? 'json' : 'md');
const output =
  format === 'json' ? JSON.stringify(paper, null, 2) : toMarkdown(paper, flag('solutions'));

const out = arg('out');
if (out) {
  writeFileSync(out, output);
  console.error(`Wrote ${paper.code} (${paper.questions.length} questions) to ${out}`);
} else {
  console.log(output);
}

function toMarkdown(p: Paper, solutions: boolean): string {
  const L = ['A', 'B', 'C', 'D'];
  const lines: string[] = [
    `# ${exam!.name} — Full Length Paper`,
    '',
    `**Paper code:** \`${p.code}\` · **Bank version:** ${BANK_VERSION} · **Questions:** ${p.questions.length} · **Time:** ${p.durationMinutes} minutes`,
    '',
    '> 200 MCQs, one mark each, no negative marking. Generated by NET CBT Simulator (unofficial practice tool; not affiliated with NUST).',
    '',
    '| Section | Questions |',
    '| --- | ---: |',
    ...p.sections.map((s) => `| ${s.title} | ${s.start + 1}–${s.start + s.count} |`),
    '',
  ];
  let lastPassage = '';
  for (const section of p.sections) {
    lines.push(`## ${section.title}`, '');
    for (const q of p.questions.slice(section.start, section.start + section.count)) {
      if (q.passage && q.passage.id !== lastPassage) {
        lastPassage = q.passage.id;
        lines.push(
          `> **Passage${q.passage.title ? `: ${q.passage.title}` : ''}**`,
          '>',
          ...q.passage.text.split('\n').map((l) => `> ${l}`),
          '',
        );
      }
      lines.push(`**${q.index + 1}.** ${q.stem}`, '');
      if (q.figure) lines.push('_(figure available in the app)_', '');
      q.options.forEach((o, i) => lines.push(`- (${L[i]}) ${o}`));
      lines.push('');
    }
  }
  lines.push(
    '## Answer key',
    '',
    '| Q | Ans | Q | Ans | Q | Ans | Q | Ans | Q | Ans |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
  );
  for (let i = 0; i < p.questions.length; i += 5) {
    const cells = p.questions.slice(i, i + 5).map((q) => `${q.index + 1} | ${L[q.correct]}`);
    while (cells.length < 5) cells.push(' | ');
    lines.push(`| ${cells.join(' | ')} |`);
  }
  if (solutions) {
    lines.push('', '## Solutions', '');
    for (const q of p.questions) {
      lines.push(
        `**${q.index + 1}.** (${L[q.correct]}) — ${chapterName(q.subject, q.chapter)}`,
        '',
        q.explanation,
        '',
      );
    }
  }
  return `${lines.join('\n')}\n`;
}
