/**
 * Curated NOUN and VERB vocabulary for the synonym / antonym / word-in-context generators in
 * `vocabulary.concepts.ts`. Adjectives live in `_lexicon.ts` (used by `vocabulary.ts`).
 * Not a chapter module itself.
 *
 * Rules for entries (same spirit as `_lexicon.ts`):
 * - `synonyms` are genuine synonyms in the sense used by `meaning` and `sentence`; `antonyms`
 *   genuine antonyms in that sense.
 * - `distractors` are hand-picked words of the same part of speech that are clearly NEITHER
 *   synonyms NOR antonyms of the headword (never near-synonyms of an antonym either).
 * - `meaning` is a short definitional phrase ("to ..." for verbs, a noun phrase for nouns);
 *   `opposite` is a definitional phrase of the OPPOSITE meaning, in the same form.
 * - `sentence` is original, uses the headword exactly once in its base form (never at the start),
 *   and makes the `meaning` sense unmistakable.
 * - `group` names a broad semantic field. Generators never borrow phrases or headwords from an
 *   entry of the same group (or one sharing any word) as distractors, so related entries such as
 *   "diminish" and "augment" can never make an option arguable.
 * - `level`: 1 = common word, 2 = typical SAT/NET word, 3 = advanced word.
 */
export interface NvEntry {
  word: string;
  pos: 'noun' | 'verb';
  level: 1 | 2 | 3;
  group: string;
  /** Headwords of other groups that are close enough in meaning never to be paired with this one. */
  avoid?: readonly string[];
  meaning: string;
  opposite: string;
  synonyms: readonly string[];
  antonyms: readonly string[];
  distractors: readonly string[];
  sentence: string;
}

export const LEXICON_NV: readonly NvEntry[] = [
  // ------------------------------------------------------------------ verbs: regard (praise / blame / like)
  { word: 'admire', pos: 'verb', level: 1, group: 'attitude', meaning: 'to regard with respect and approval', opposite: 'to regard with contempt', synonyms: ['respect', 'esteem'], antonyms: ['despise', 'scorn'], distractors: ['borrow', 'sweep', 'measure', 'knit'], sentence: 'Students admire a teacher who treats everyone fairly.' },
  { word: 'commend', pos: 'verb', level: 2, group: 'attitude', meaning: 'to praise formally or officially', opposite: 'to criticise severely', synonyms: ['praise', 'laud'], antonyms: ['criticise', 'condemn'], distractors: ['borrow', 'measure', 'stitch', 'rinse'], sentence: 'The principal rose to commend the volunteers for their hard work.' },
  { word: 'censure', pos: 'verb', level: 3, group: 'attitude', meaning: 'to express severe formal disapproval of', opposite: 'to praise formally', synonyms: ['rebuke', 'reprimand'], antonyms: ['commend', 'praise'], distractors: ['ponder', 'irrigate', 'tabulate', 'engrave'], sentence: 'Parliament voted to censure the minister for misleading the House.' },
  { word: 'extol', pos: 'verb', level: 3, group: 'attitude', meaning: 'to praise enthusiastically', opposite: 'to speak of as worthless', synonyms: ['laud', 'glorify'], antonyms: ['disparage', 'belittle'], distractors: ['irrigate', 'recline', 'transcribe', 'fumigate'], sentence: 'Critics continue to extol the novel for its honesty.' },
  { word: 'ridicule', pos: 'verb', level: 2, group: 'attitude', meaning: 'to make fun of in an unkind way', opposite: 'to speak of with respect', synonyms: ['mock', 'deride'], antonyms: ['respect', 'praise'], distractors: ['inherit', 'translate', 'stitch', 'rinse'], sentence: 'It is cruel to ridicule a classmate for a stammer.' },
  { word: 'detest', pos: 'verb', level: 2, group: 'attitude', meaning: 'to dislike intensely', opposite: 'to like very much', synonyms: ['hate', 'loathe'], antonyms: ['love', 'adore'], distractors: ['translate', 'inherit', 'sketch', 'rinse'], sentence: 'Most cats detest getting wet.' },
  { word: 'cherish', pos: 'verb', level: 2, group: 'attitude', avoid: ['conserve', 'defend', 'squander'], meaning: 'to hold dear and keep with love', opposite: 'to treat as worthless', synonyms: ['treasure', 'prize'], antonyms: ['despise', 'disregard'], distractors: ['translate', 'whistle', 'stitch', 'sketch'], sentence: 'She will always cherish the memory of her grandmother.' },
  { word: 'neglect', pos: 'verb', level: 2, group: 'attitude', avoid: ['conserve', 'defend', 'repair', 'confront'], meaning: 'to fail to give proper care or attention to', opposite: 'to look after with great care', synonyms: ['ignore', 'disregard'], antonyms: ['tend', 'cherish'], distractors: ['translate', 'whistle', 'imitate', 'stitch'], sentence: 'Busy parents sometimes neglect their own health.' },

  // ------------------------------------------------------------------ verbs: reveal / hide
  { word: 'conceal', pos: 'verb', level: 1, group: 'knowledge', meaning: 'to keep from sight or knowledge', opposite: 'to make known or visible', synonyms: ['hide', 'mask'], antonyms: ['reveal', 'expose'], distractors: ['borrow', 'measure', 'knit', 'bake'], sentence: 'He tried to conceal his disappointment behind a smile.' },
  { word: 'divulge', pos: 'verb', level: 3, group: 'knowledge', meaning: 'to make known something private or secret', opposite: 'to keep something secret', synonyms: ['disclose', 'reveal'], antonyms: ['conceal', 'withhold'], distractors: ['irrigate', 'engrave', 'recline', 'tabulate'], sentence: 'The journalist refused to divulge the name of her source.' },
  { word: 'emerge', pos: 'verb', level: 2, group: 'knowledge', avoid: ['depart', 'evade', 'ascend'], meaning: 'to come out into view', opposite: 'to pass out of view', synonyms: ['appear', 'surface'], antonyms: ['vanish', 'disappear'], distractors: ['inherit', 'translate', 'stitch', 'imitate'], sentence: 'Divers watched a turtle emerge from the shadow of the reef.' },

  // ------------------------------------------------------------------ verbs: size and intensity
  { word: 'expand', pos: 'verb', level: 1, group: 'change', meaning: 'to make or become larger', opposite: 'to make or become smaller', synonyms: ['enlarge', 'extend'], antonyms: ['contract', 'shrink'], distractors: ['whisper', 'borrow', 'sneeze', 'bake'], sentence: 'The company plans to expand its factory next year.' },
  { word: 'diminish', pos: 'verb', level: 2, group: 'change', meaning: 'to make or become less', opposite: 'to make or become greater', synonyms: ['lessen', 'decrease'], antonyms: ['increase', 'augment'], distractors: ['inherit', 'decorate', 'translate', 'whistle'], sentence: 'Nothing could diminish her enthusiasm for the project.' },
  { word: 'augment', pos: 'verb', level: 3, group: 'change', meaning: 'to make greater by adding to', opposite: 'to make smaller by taking away', synonyms: ['increase', 'supplement'], antonyms: ['reduce', 'diminish'], distractors: ['salute', 'transcribe', 'recline', 'engrave'], sentence: 'He took a part-time job to augment his income.' },
  { word: 'curtail', pos: 'verb', level: 3, group: 'change', meaning: 'to cut short or restrict', opposite: 'to lengthen or widen', synonyms: ['reduce', 'restrict'], antonyms: ['extend', 'prolong'], distractors: ['salute', 'engrave', 'fumigate', 'transcribe'], sentence: 'The city had to curtail its spending after the floods.' },
  { word: 'dwindle', pos: 'verb', level: 2, group: 'change', meaning: 'to become gradually smaller', opposite: 'to grow steadily larger', synonyms: ['shrink', 'decline'], antonyms: ['grow', 'increase'], distractors: ['whistle', 'imitate', 'stitch', 'inherit'], sentence: 'Without rain, the stream began to dwindle to a trickle.' },
  { word: 'abbreviate', pos: 'verb', level: 2, group: 'change', meaning: 'to shorten a word, phrase or text', opposite: 'to make a word or text longer', synonyms: ['shorten', 'abridge'], antonyms: ['lengthen', 'expand'], distractors: ['whistle', 'inherit', 'rinse', 'imitate'], sentence: 'The editor asked him to abbreviate his long article.' },
  { word: 'abate', pos: 'verb', level: 3, group: 'change', meaning: 'to become less strong or intense', opposite: 'to become more strong or intense', synonyms: ['subside', 'wane'], antonyms: ['intensify', 'escalate'], distractors: ['engrave', 'salute', 'tabulate', 'transcribe'], sentence: 'We waited for the storm to abate before setting out.' },
  { word: 'escalate', pos: 'verb', level: 2, group: 'change', meaning: 'to increase rapidly in intensity or seriousness', opposite: 'to become calmer and less serious', synonyms: ['intensify', 'heighten'], antonyms: ['subside', 'lessen'], distractors: ['imitate', 'translate', 'inherit', 'stitch'], sentence: 'Officials feared the quarrel would escalate into violence.' },
  { word: 'exaggerate', pos: 'verb', level: 1, group: 'change', meaning: 'to describe something as greater than it really is', opposite: 'to describe something as smaller than it really is', synonyms: ['overstate', 'magnify'], antonyms: ['understate', 'minimise'], distractors: ['borrow', 'sweep', 'sneeze', 'bake'], sentence: 'Anglers often exaggerate the size of their catch.' },

  // ------------------------------------------------------------------ verbs: condition (build / improve / harm)
  { word: 'construct', pos: 'verb', level: 1, group: 'change', meaning: 'to build something', opposite: 'to knock something down', synonyms: ['build', 'erect'], antonyms: ['demolish', 'destroy'], distractors: ['whisper', 'borrow', 'sneeze', 'measure'], sentence: 'Engineers will construct a new bridge across the river.' },
  { word: 'demolish', pos: 'verb', level: 2, group: 'change', meaning: 'to pull or knock down a building', opposite: 'to put up a building', synonyms: ['raze', 'destroy'], antonyms: ['build', 'erect'], distractors: ['whistle', 'translate', 'imitate', 'rinse'], sentence: 'Workers began to demolish the old cinema on Monday.' },
  { word: 'repair', pos: 'verb', level: 1, group: 'change', avoid: ['conserve'], meaning: 'to put something damaged back into good condition', opposite: 'to cause damage to something', synonyms: ['mend', 'fix'], antonyms: ['break', 'damage'], distractors: ['whisper', 'borrow', 'measure', 'sneeze'], sentence: 'The mechanic will repair the engine by Friday.' },
  { word: 'deteriorate', pos: 'verb', level: 2, group: 'change', meaning: 'to become progressively worse', opposite: 'to become progressively better', synonyms: ['worsen', 'decline'], antonyms: ['improve', 'recover'], distractors: ['whistle', 'translate', 'inherit', 'sketch'], sentence: 'Old books deteriorate quickly in damp rooms.' },
  { word: 'ameliorate', pos: 'verb', level: 3, group: 'change', meaning: 'to make a bad situation better', opposite: 'to make a bad situation worse', synonyms: ['improve', 'better'], antonyms: ['worsen', 'aggravate'], distractors: ['tabulate', 'recline', 'engrave', 'transcribe'], sentence: 'The charity works to ameliorate living conditions in the slums.' },
  { word: 'aggravate', pos: 'verb', level: 3, group: 'change', avoid: ['provoke', 'soothe', 'pacify'], meaning: 'to make a problem or injury worse', opposite: 'to make a problem or injury less severe', synonyms: ['worsen', 'exacerbate'], antonyms: ['alleviate', 'relieve'], distractors: ['salute', 'transcribe', 'tabulate', 'engrave'], sentence: 'Scratching will only aggravate the rash.' },
  { word: 'alleviate', pos: 'verb', level: 2, group: 'change', meaning: 'to make pain or suffering less severe', opposite: 'to make pain or suffering more severe', synonyms: ['relieve', 'ease'], antonyms: ['aggravate', 'intensify'], distractors: ['inherit', 'translate', 'whistle', 'stitch'], sentence: 'The medicine helped to alleviate the pain in his back.' },
  { word: 'flourish', pos: 'verb', level: 2, group: 'change', meaning: 'to grow or develop successfully', opposite: 'to weaken and fail', synonyms: ['thrive', 'prosper'], antonyms: ['decline', 'wither'], distractors: ['whistle', 'inherit', 'stitch', 'imitate'], sentence: 'Small businesses flourish when the economy is stable.' },
  { word: 'languish', pos: 'verb', level: 3, group: 'change', meaning: 'to grow weak or fail to make progress', opposite: 'to grow strong and successful', synonyms: ['wither', 'decline'], antonyms: ['flourish', 'thrive'], distractors: ['engrave', 'tabulate', 'irrigate', 'salute'], sentence: 'Without investment, the old mills will languish for years.' },
  { word: 'strengthen', pos: 'verb', level: 1, group: 'change', avoid: ['corroborate'], meaning: 'to make stronger', opposite: 'to make weaker', synonyms: ['reinforce', 'fortify'], antonyms: ['weaken', 'undermine'], distractors: ['borrow', 'whisper', 'sneeze', 'knit'], sentence: 'Regular exercise will strengthen your muscles.' },
  { word: 'undermine', pos: 'verb', level: 3, group: 'change', avoid: ['corroborate', 'verify', 'refute'], meaning: 'to weaken gradually or secretly', opposite: 'to support and make stronger', synonyms: ['weaken', 'subvert'], antonyms: ['strengthen', 'support'], distractors: ['engrave', 'irrigate', 'salute', 'tabulate'], sentence: "Constant criticism can undermine a child's confidence." },
  { word: 'bolster', pos: 'verb', level: 3, group: 'change', avoid: ['corroborate', 'verify', 'refute'], meaning: 'to support or strengthen', opposite: 'to weaken or damage', synonyms: ['reinforce', 'boost'], antonyms: ['undermine', 'weaken'], distractors: ['transcribe', 'recline', 'fumigate', 'irrigate'], sentence: "The early goal helped to bolster the team's morale." },

  // ------------------------------------------------------------------ verbs: help / hinder
  { word: 'assist', pos: 'verb', level: 1, group: 'change', meaning: 'to help someone', opposite: 'to get in the way of someone', synonyms: ['help', 'aid'], antonyms: ['hinder', 'obstruct'], distractors: ['borrow', 'measure', 'sneeze', 'knit'], sentence: 'Volunteers came forward to assist the flood victims.' },
  { word: 'hinder', pos: 'verb', level: 2, group: 'change', meaning: 'to make progress difficult', opposite: 'to help progress along', synonyms: ['hamper', 'obstruct'], antonyms: ['help', 'facilitate'], distractors: ['decorate', 'inherit', 'whistle', 'sketch'], sentence: 'Heavy snow continued to hinder the rescue effort.' },
  { word: 'impede', pos: 'verb', level: 3, group: 'change', meaning: 'to delay or block the progress of', opposite: 'to speed up the progress of', synonyms: ['obstruct', 'hamper'], antonyms: ['facilitate', 'expedite'], distractors: ['engrave', 'recline', 'transcribe', 'fumigate'], sentence: 'Fallen trees impede the flow of traffic after every storm.' },
  { word: 'facilitate', pos: 'verb', level: 2, group: 'change', meaning: 'to make an action or process easier', opposite: 'to make an action or process harder', synonyms: ['ease', 'assist'], antonyms: ['hinder', 'impede'], distractors: ['imitate', 'whistle', 'rinse', 'sketch'], sentence: 'Clear signs facilitate the movement of visitors through the museum.' },
  { word: 'thwart', pos: 'verb', level: 3, group: 'change', meaning: 'to prevent someone from carrying out a plan', opposite: 'to help someone carry out a plan', synonyms: ['foil', 'frustrate'], antonyms: ['aid', 'assist'], distractors: ['transcribe', 'recline', 'tabulate', 'fumigate'], sentence: 'Alert guards managed to thwart the robbery.' },

  // ------------------------------------------------------------------ verbs: permit / accept / include
  { word: 'permit', pos: 'verb', level: 1, group: 'attitude', meaning: 'to allow something to happen', opposite: 'to refuse to allow something', synonyms: ['allow', 'authorise'], antonyms: ['forbid', 'prohibit'], distractors: ['borrow', 'sweep', 'sneeze', 'bake'], sentence: 'The rules do not permit mobile phones in the examination hall.' },
  { word: 'prohibit', pos: 'verb', level: 2, group: 'attitude', avoid: ['thwart'], meaning: 'to forbid by law or rule', opposite: 'to allow by law or rule', synonyms: ['ban', 'forbid'], antonyms: ['allow', 'permit'], distractors: ['decorate', 'inherit', 'whistle', 'sketch'], sentence: 'The new law will prohibit smoking in public places.' },
  { word: 'reject', pos: 'verb', level: 1, group: 'attitude', avoid: ['deny', 'refute'], meaning: 'to refuse to accept', opposite: 'to agree to take', synonyms: ['refuse', 'decline'], antonyms: ['accept', 'approve'], distractors: ['measure', 'sneeze', 'whisper', 'knit'], sentence: 'The committee may reject the proposal if it costs too much.' },
  { word: 'spurn', pos: 'verb', level: 3, group: 'attitude', meaning: 'to reject with contempt', opposite: 'to accept gladly', synonyms: ['rebuff', 'scorn'], antonyms: ['welcome', 'embrace'], distractors: ['tabulate', 'irrigate', 'recline', 'engrave'], sentence: 'She chose to spurn every offer of help from her rivals.' },
  { word: 'exclude', pos: 'verb', level: 1, group: 'attitude', meaning: 'to deliberately leave out', opposite: 'to take in as part of a whole', synonyms: ['omit', 'bar'], antonyms: ['include', 'admit'], distractors: ['sneeze', 'measure', 'whisper', 'bake'], sentence: 'The final list will exclude anyone who missed the deadline.' },
  { word: 'expel', pos: 'verb', level: 2, group: 'attitude', avoid: ['disperse', 'depart', 'confine', 'gather'], meaning: 'to force someone to leave a place or group', opposite: 'to let someone enter a place or group', synonyms: ['eject', 'oust'], antonyms: ['admit', 'welcome'], distractors: ['decorate', 'imitate', 'whistle', 'sketch'], sentence: 'The school may expel students who cheat repeatedly.' },

  // ------------------------------------------------------------------ verbs: gather / join / separate
  { word: 'gather', pos: 'verb', level: 1, group: 'place', meaning: 'to bring together into one place', opposite: 'to spread in different directions', synonyms: ['collect', 'assemble'], antonyms: ['scatter', 'disperse'], distractors: ['whisper', 'sneeze', 'borrow', 'bake'], sentence: 'Before the storm, the farmers gather their sheep into the fold.' },
  { word: 'disperse', pos: 'verb', level: 2, group: 'place', meaning: 'to go or send in different directions', opposite: 'to come together in one place', synonyms: ['scatter', 'dissipate'], antonyms: ['gather', 'assemble'], distractors: ['decorate', 'imitate', 'inherit', 'stitch'], sentence: 'The police asked the crowd to disperse peacefully.' },
  { word: 'unite', pos: 'verb', level: 1, group: 'place', meaning: 'to join together for a common purpose', opposite: 'to split into separate parts', synonyms: ['join', 'combine'], antonyms: ['divide', 'separate'], distractors: ['borrow', 'measure', 'sneeze', 'whisper'], sentence: 'A common danger can unite even old rivals.' },
  { word: 'merge', pos: 'verb', level: 2, group: 'place', meaning: 'to combine into a single whole', opposite: 'to break into separate parts', synonyms: ['combine', 'amalgamate'], antonyms: ['separate', 'split'], distractors: ['whistle', 'translate', 'sketch', 'rinse'], sentence: 'The two banks will merge next spring.' },
  { word: 'sever', pos: 'verb', level: 3, group: 'place', avoid: ['curtail', 'terminate', 'abbreviate'], meaning: 'to cut off or break off completely', opposite: 'to link or connect firmly', synonyms: ['cut', 'break off'], antonyms: ['join', 'connect'], distractors: ['ponder', 'irrigate', 'salute', 'recline'], sentence: 'The two countries decided to sever diplomatic ties.' },

  // ------------------------------------------------------------------ verbs: movement / avoidance
  { word: 'ascend', pos: 'verb', level: 2, group: 'place', avoid: ['escalate'], meaning: 'to go or climb up', opposite: 'to go or climb down', synonyms: ['climb', 'mount'], antonyms: ['descend', 'fall'], distractors: ['whistle', 'translate', 'decorate', 'inherit'], sentence: 'The climbers will ascend the peak at dawn.' },
  { word: 'depart', pos: 'verb', level: 1, group: 'place', avoid: ['commence'], meaning: 'to leave, especially to begin a journey', opposite: 'to reach the end of a journey', synonyms: ['leave', 'exit'], antonyms: ['arrive'], distractors: ['borrow', 'measure', 'whisper', 'knit'], sentence: 'The train will depart from platform two at noon.' },
  { word: 'evade', pos: 'verb', level: 2, group: 'place', meaning: 'to escape or avoid, especially by cleverness', opposite: 'to face directly', synonyms: ['avoid', 'dodge'], antonyms: ['confront', 'face'], distractors: ['decorate', 'inherit', 'whistle', 'rinse'], sentence: "The minister tried to evade the reporter's questions." },
  { word: 'confront', pos: 'verb', level: 2, group: 'place', meaning: 'to face up to and deal with', opposite: 'to keep away from', synonyms: ['face', 'tackle'], antonyms: ['avoid', 'evade'], distractors: ['whistle', 'translate', 'sketch', 'stitch'], sentence: 'Sooner or later we must confront the problem of pollution.' },
  { word: 'abandon', pos: 'verb', level: 1, group: 'attitude', avoid: ['depart', 'forfeit', 'squander', 'terminate', 'sever', 'acquire'], meaning: 'to leave a person, place or thing for ever', opposite: 'to keep and look after', synonyms: ['desert', 'forsake'], antonyms: ['keep', 'retain'], distractors: ['whisper', 'measure', 'sneeze', 'bake'], sentence: 'The crew had to abandon the sinking ship and swim to the lifeboats.' },

  // ------------------------------------------------------------------ verbs: mind / truth
  { word: 'recall', pos: 'verb', level: 1, group: 'knowledge', meaning: 'to bring back to mind', opposite: 'to fail to remember', synonyms: ['remember', 'recollect'], antonyms: ['forget'], distractors: ['carry', 'sweep', 'bake', 'knit'], sentence: 'I cannot recall the name of the hotel where we stayed.' },
  { word: 'verify', pos: 'verb', level: 2, group: 'knowledge', meaning: 'to check or show that something is true', opposite: 'to show that something is false', synonyms: ['confirm', 'check'], antonyms: ['disprove', 'refute'], distractors: ['decorate', 'whistle', 'imitate', 'rinse'], sentence: 'Further tests are needed to verify the results.' },
  { word: 'refute', pos: 'verb', level: 3, group: 'knowledge', meaning: 'to prove a statement or claim to be false', opposite: 'to prove a statement or claim to be true', synonyms: ['disprove', 'rebut'], antonyms: ['confirm', 'prove'], distractors: ['irrigate', 'salute', 'recline', 'fumigate'], sentence: 'The lawyer produced documents to refute the charge.' },
  { word: 'corroborate', pos: 'verb', level: 3, group: 'knowledge', meaning: 'to confirm or support with evidence', opposite: 'to go against with evidence', synonyms: ['confirm', 'substantiate'], antonyms: ['contradict', 'refute'], distractors: ['engrave', 'tabulate', 'irrigate', 'fumigate'], sentence: 'Two witnesses were able to corroborate her story.' },
  { word: 'deny', pos: 'verb', level: 1, group: 'knowledge', avoid: ['prohibit', 'spurn'], meaning: 'to state that something is not true', opposite: 'to accept that something is true', synonyms: ['contradict', 'dispute'], antonyms: ['admit', 'confirm'], distractors: ['borrow', 'sweep', 'knit', 'bake'], sentence: 'The company was quick to deny the rumours of a merger.' },
  { word: 'clarify', pos: 'verb', level: 2, group: 'knowledge', avoid: ['facilitate'], meaning: 'to make clearer or easier to understand', opposite: 'to make harder to understand', synonyms: ['explain', 'elucidate'], antonyms: ['confuse', 'obscure'], distractors: ['inherit', 'whistle', 'stitch', 'rinse'], sentence: 'Could you clarify what you meant by your last remark?' },

  // ------------------------------------------------------------------ verbs: obey / defend / protect / free
  { word: 'obey', pos: 'verb', level: 1, group: 'attitude', meaning: 'to do what a rule or person commands', opposite: 'to refuse to do what is commanded', synonyms: ['follow', 'heed'], antonyms: ['disobey', 'defy'], distractors: ['borrow', 'measure', 'sneeze', 'bake'], sentence: 'Drivers must obey the traffic signals at all times.' },
  { word: 'defy', pos: 'verb', level: 2, group: 'attitude', avoid: ['confront'], meaning: 'to openly refuse to obey', opposite: 'to do what is commanded', synonyms: ['disobey', 'resist'], antonyms: ['obey', 'comply'], distractors: ['decorate', 'imitate', 'whistle', 'sketch'], sentence: 'The protesters chose to defy the curfew.' },
  { word: 'defend', pos: 'verb', level: 1, group: 'place', avoid: ['undermine', 'bolster', 'strengthen'], meaning: 'to protect from attack', opposite: 'to launch an attack on', synonyms: ['protect', 'guard'], antonyms: ['attack', 'assault'], distractors: ['borrow', 'measure', 'sneeze', 'knit'], sentence: 'Soldiers were sent to defend the border town.' },
  { word: 'conserve', pos: 'verb', level: 2, group: 'place', meaning: 'to protect from harm, loss or waste', opposite: 'to use up carelessly', synonyms: ['preserve', 'save'], antonyms: ['waste', 'squander'], distractors: ['imitate', 'whistle', 'sketch', 'stitch'], sentence: 'We must conserve water during the dry season.' },
  { word: 'squander', pos: 'verb', level: 2, group: 'place', meaning: 'to waste in a reckless or foolish way', opposite: 'to use with care and save', synonyms: ['waste', 'fritter away'], antonyms: ['save', 'conserve'], distractors: ['decorate', 'whistle', 'translate', 'stitch'], sentence: 'Do not squander your savings on things you do not need.' },
  { word: 'liberate', pos: 'verb', level: 2, group: 'place', meaning: 'to set free', opposite: 'to hold captive', synonyms: ['free', 'release'], antonyms: ['imprison', 'enslave'], distractors: ['decorate', 'translate', 'sketch', 'rinse'], sentence: 'The army marched in to liberate the captured city.' },
  { word: 'confine', pos: 'verb', level: 2, group: 'place', avoid: ['expel', 'exclude'], meaning: 'to keep within certain limits', opposite: 'to set free from limits', synonyms: ['restrict', 'restrain'], antonyms: ['free', 'release'], distractors: ['imitate', 'whistle', 'sketch', 'rinse'], sentence: 'The doctor decided to confine the patient to bed for a week.' },

  // ------------------------------------------------------------------ verbs: gain / lose
  { word: 'purchase', pos: 'verb', level: 1, group: 'place', meaning: 'to obtain by paying money', opposite: 'to give in exchange for money', synonyms: ['buy', 'acquire'], antonyms: ['sell'], distractors: ['whisper', 'sneeze', 'knit', 'sweep'], sentence: 'We plan to purchase a new car this year.' },
  { word: 'acquire', pos: 'verb', level: 2, group: 'place', meaning: 'to gain possession of', opposite: 'to lose possession of', synonyms: ['obtain', 'gain'], antonyms: ['lose', 'forfeit'], distractors: ['whistle', 'decorate', 'translate', 'rinse'], sentence: 'It takes years to acquire fluency in a new language.' },
  { word: 'forfeit', pos: 'verb', level: 3, group: 'place', avoid: ['cherish'], meaning: 'to lose or give up as a penalty', opposite: 'to keep or win', synonyms: ['lose', 'surrender'], antonyms: ['gain', 'retain'], distractors: ['engrave', 'ponder', 'transcribe', 'fumigate'], sentence: 'Any team that arrives late will forfeit the match.' },

  // ------------------------------------------------------------------ verbs: urge / calm
  { word: 'encourage', pos: 'verb', level: 1, group: 'change', avoid: ['commend', 'corroborate'], meaning: 'to give support, confidence or hope to', opposite: 'to take away confidence or hope from', synonyms: ['inspire', 'hearten'], antonyms: ['discourage', 'dishearten'], distractors: ['borrow', 'measure', 'sweep', 'sneeze'], sentence: 'Parents should encourage children to read for pleasure.' },
  { word: 'deter', pos: 'verb', level: 2, group: 'change', meaning: 'to discourage from acting, especially through fear', opposite: 'to urge on to act', synonyms: ['discourage', 'dissuade'], antonyms: ['encourage', 'motivate'], distractors: ['decorate', 'inherit', 'whistle', 'sketch'], sentence: 'High fines are meant to deter people from littering.' },
  { word: 'soothe', pos: 'verb', level: 2, group: 'attitude', avoid: ['alleviate', 'ameliorate', 'escalate', 'abate'], meaning: 'to make calm or less painful', opposite: 'to make upset or more painful', synonyms: ['calm', 'comfort'], antonyms: ['agitate', 'irritate'], distractors: ['translate', 'inherit', 'sketch', 'stitch'], sentence: 'A gentle song can soothe a restless baby.' },
  { word: 'pacify', pos: 'verb', level: 3, group: 'attitude', avoid: ['escalate', 'abate', 'alleviate'], meaning: 'to calm the anger of', opposite: 'to stir up the anger of', synonyms: ['placate', 'appease'], antonyms: ['provoke', 'enrage'], distractors: ['tabulate', 'engrave', 'transcribe', 'recline'], sentence: 'The manager tried to pacify the angry customers with refunds.' },
  { word: 'provoke', pos: 'verb', level: 2, group: 'attitude', avoid: ['escalate', 'abate'], meaning: 'to deliberately make angry', opposite: 'to deliberately calm down', synonyms: ['anger', 'enrage'], antonyms: ['pacify', 'soothe'], distractors: ['decorate', 'inherit', 'rinse', 'imitate'], sentence: 'Do not provoke the dog by pulling its tail.' },

  // ------------------------------------------------------------------ verbs: time (begin / end / speed)
  { word: 'commence', pos: 'verb', level: 2, group: 'change', meaning: 'to begin', opposite: 'to come to an end', synonyms: ['begin', 'start'], antonyms: ['end', 'conclude'], distractors: ['imitate', 'whistle', 'stitch', 'rinse'], sentence: 'The ceremony will commence with a recitation.' },
  { word: 'terminate', pos: 'verb', level: 2, group: 'change', meaning: 'to bring to an end', opposite: 'to set going', synonyms: ['end', 'discontinue'], antonyms: ['begin', 'start'], distractors: ['decorate', 'whistle', 'sketch', 'inherit'], sentence: 'The firm may terminate the contract without notice.' },
  { word: 'hasten', pos: 'verb', level: 2, group: 'change', meaning: 'to cause to happen sooner', opposite: 'to cause to happen later', synonyms: ['accelerate', 'quicken'], antonyms: ['delay', 'slow'], distractors: ['decorate', 'imitate', 'inherit', 'stitch'], sentence: 'Fresh air and rest will hasten her recovery.' },

  // ------------------------------------------------------------------ verbs: agreement and mercy
  { word: 'concur', pos: 'verb', level: 3, group: 'attitude', avoid: ['unite', 'merge', 'disperse', 'sever', 'corroborate', 'verify', 'deny', 'refute'], meaning: 'to be of the same opinion', opposite: 'to be of a different opinion', synonyms: ['agree'], antonyms: ['disagree', 'differ'], distractors: ['engrave', 'irrigate', 'tabulate', 'fumigate'], sentence: 'Most experts concur with the findings of the report.' },
  { word: 'pardon', pos: 'verb', level: 2, group: 'attitude', avoid: ['liberate'], meaning: 'to forgive someone for an offence', opposite: 'to make someone suffer for an offence', synonyms: ['forgive', 'excuse'], antonyms: ['punish', 'penalise'], distractors: ['measure', 'decorate', 'sketch', 'rinse'], sentence: 'She found it hard to pardon her brother for breaking his promise.' },
  { word: 'condone', pos: 'verb', level: 3, group: 'attitude', meaning: 'to accept or overlook wrongdoing', opposite: 'to declare wrongdoing unacceptable', synonyms: ['overlook', 'excuse'], antonyms: ['condemn', 'denounce'], distractors: ['irrigate', 'tabulate', 'recline', 'transcribe'], sentence: 'The school will not condone bullying of any kind.' },

  // ------------------------------------------------------------------ nouns: quantity
  { word: 'abundance', pos: 'noun', level: 1, group: 'quantity', meaning: 'a very large quantity of something', opposite: 'a serious lack of something', synonyms: ['plenty', 'profusion'], antonyms: ['scarcity', 'shortage'], distractors: ['ladder', 'journey', 'blanket', 'kettle'], sentence: 'The region has an abundance of fresh fruit in summer.' },
  { word: 'scarcity', pos: 'noun', level: 2, group: 'quantity', meaning: 'the state of being in short supply', opposite: 'the state of being plentiful', synonyms: ['shortage', 'dearth'], antonyms: ['abundance', 'plenty'], distractors: ['ceremony', 'souvenir', 'pendulum', 'carnival'], sentence: 'The scarcity of clean water worries the villagers.' },
  { word: 'dearth', pos: 'noun', level: 3, group: 'quantity', meaning: 'a lack or inadequate amount of something', opposite: 'a more than adequate amount of something', synonyms: ['scarcity', 'paucity'], antonyms: ['abundance', 'surplus'], distractors: ['lullaby', 'tariff', 'sonnet', 'pilgrimage'], sentence: 'There is a dearth of trained teachers in rural schools.' },
  { word: 'plethora', pos: 'noun', level: 3, group: 'quantity', meaning: 'an excessive amount of something', opposite: 'too small an amount of something', synonyms: ['excess', 'surfeit'], antonyms: ['lack', 'dearth'], distractors: ['mosaic', 'tariff', 'almanac', 'pilgrimage'], sentence: 'The report contained a plethora of statistics but few conclusions.' },
  { word: 'surplus', pos: 'noun', level: 2, group: 'quantity', meaning: 'an amount left over beyond what is needed', opposite: 'an amount by which something falls short', synonyms: ['excess', 'glut'], antonyms: ['deficit', 'shortage'], distractors: ['ceremony', 'souvenir', 'pendulum', 'carnival'], sentence: 'The farm sold its surplus of wheat to neighbouring villages.' },

  // ------------------------------------------------------------------ nouns: bravery
  { word: 'courage', pos: 'noun', level: 1, group: 'mood', meaning: 'the ability to face danger or pain without fear', opposite: 'the inability to face danger or pain', synonyms: ['bravery', 'valour'], antonyms: ['cowardice', 'fear'], distractors: ['ladder', 'journey', 'kettle', 'umbrella'], sentence: 'It took great courage to speak out against the injustice.' },
  { word: 'cowardice', pos: 'noun', level: 2, group: 'mood', meaning: 'a lack of bravery', opposite: 'a readiness to face danger', synonyms: ['timidity', 'fearfulness'], antonyms: ['courage', 'bravery'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'The soldier was accused of cowardice for fleeing the battle.' },
  { word: 'audacity', pos: 'noun', level: 3, group: 'mood', avoid: ['arrogance', 'humility'], meaning: 'a willingness to take bold risks', opposite: 'an unwillingness to take any risk', synonyms: ['boldness', 'daring'], antonyms: ['timidity', 'caution'], distractors: ['lullaby', 'tariff', 'mosaic', 'almanac'], sentence: 'Few expected the young player to have the audacity to attack the champion.' },

  // ------------------------------------------------------------------ nouns: regard (praise / blame / feeling)
  { word: 'criticism', pos: 'noun', level: 1, group: 'relations', meaning: 'the expression of disapproval', opposite: 'the expression of approval', synonyms: ['censure', 'disapproval'], antonyms: ['praise', 'approval'], distractors: ['ladder', 'journey', 'blanket', 'kettle'], sentence: 'The new policy drew sharp criticism from the opposition.' },
  { word: 'eulogy', pos: 'noun', level: 3, group: 'relations', meaning: 'a speech or piece of writing that praises someone highly', opposite: 'a speech or piece of writing that attacks someone', synonyms: ['tribute', 'panegyric'], antonyms: ['condemnation', 'denunciation'], distractors: ['tariff', 'mosaic', 'almanac', 'pilgrimage'], sentence: 'Her oldest friend delivered a moving eulogy at the funeral.' },
  { word: 'acclaim', pos: 'noun', level: 2, group: 'relations', avoid: ['renown', 'obscurity', 'merit'], meaning: 'enthusiastic public praise', opposite: 'widespread public disapproval', synonyms: ['praise', 'applause'], antonyms: ['criticism', 'disapproval'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: "The young author's first novel won wide acclaim." },
  { word: 'gratitude', pos: 'noun', level: 1, group: 'relations', meaning: 'the quality of being thankful', opposite: 'the quality of being unthankful', synonyms: ['thankfulness', 'appreciation'], antonyms: ['ingratitude', 'ungratefulness'], distractors: ['ladder', 'blanket', 'kettle', 'umbrella'], sentence: 'She wrote to the doctors to express her gratitude.' },
  { word: 'arrogance', pos: 'noun', level: 1, group: 'relations', meaning: "an exaggerated sense of one's own importance", opposite: "a modest view of one's own importance", synonyms: ['conceit', 'haughtiness'], antonyms: ['humility', 'modesty'], distractors: ['ladder', 'journey', 'blanket', 'kettle'], sentence: 'His arrogance made him unpopular with his classmates.' },
  { word: 'humility', pos: 'noun', level: 2, group: 'relations', meaning: "a modest view of one's own importance", opposite: "an inflated view of one's own importance", synonyms: ['modesty', 'humbleness'], antonyms: ['arrogance', 'pride'], distractors: ['ceremony', 'souvenir', 'pendulum', 'orchard'], sentence: 'Despite her fame, she was admired for her humility.' },

  // ------------------------------------------------------------------ nouns: honesty
  { word: 'honesty', pos: 'noun', level: 1, group: 'honesty', meaning: 'the quality of being truthful', opposite: 'the quality of being untruthful', synonyms: ['integrity', 'sincerity'], antonyms: ['dishonesty', 'deceit'], distractors: ['ladder', 'journey', 'kettle', 'umbrella'], sentence: 'Everyone respects the shopkeeper for his honesty.' },
  { word: 'deceit', pos: 'noun', level: 2, group: 'honesty', meaning: 'the act of making someone believe something false', opposite: 'the practice of being open and truthful', synonyms: ['deception', 'trickery'], antonyms: ['honesty', 'candour'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'The whole scheme was built on lies and deceit.' },
  { word: 'candour', pos: 'noun', level: 3, group: 'honesty', meaning: 'the quality of being open and frank', opposite: 'the quality of being secretive and evasive', synonyms: ['frankness', 'openness'], antonyms: ['deceit', 'evasiveness'], distractors: ['tariff', 'lullaby', 'mosaic', 'almanac'], sentence: 'The minister spoke with surprising candour about his mistakes.' },
  { word: 'hypocrisy', pos: 'noun', level: 2, group: 'honesty', meaning: 'the pretence of having virtues one does not have', opposite: 'genuine and open honesty of feeling', synonyms: ['insincerity', 'pretence'], antonyms: ['sincerity', 'honesty'], distractors: ['ceremony', 'carnival', 'pendulum', 'orchard'], sentence: 'Voters were angered by the hypocrisy of a leader who preached thrift but lived lavishly.' },

  // ------------------------------------------------------------------ nouns: relations (peace / conflict / mercy / allies)
  { word: 'harmony', pos: 'noun', level: 1, group: 'relations', meaning: 'peaceful agreement between people', opposite: 'angry disagreement between people', synonyms: ['accord', 'concord'], antonyms: ['discord', 'conflict'], distractors: ['ladder', 'journey', 'blanket', 'kettle'], sentence: 'The neighbours lived in harmony for many years.' },
  { word: 'hostility', pos: 'noun', level: 2, group: 'relations', meaning: 'unfriendly or aggressive behaviour', opposite: 'friendly and welcoming behaviour', synonyms: ['animosity', 'enmity'], antonyms: ['friendliness', 'goodwill'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'There was open hostility between the two rival gangs.' },
  { word: 'animosity', pos: 'noun', level: 3, group: 'relations', meaning: 'strong dislike or hatred', opposite: 'warm and friendly feeling', synonyms: ['hostility', 'antagonism'], antonyms: ['friendship', 'goodwill'], distractors: ['tariff', 'mosaic', 'lullaby', 'almanac'], sentence: 'Years of rivalry left deep animosity between the families.' },
  { word: 'discord', pos: 'noun', level: 2, group: 'relations', avoid: ['consent'], meaning: 'disagreement and quarrelling between people', opposite: 'agreement and goodwill between people', synonyms: ['conflict', 'strife'], antonyms: ['harmony', 'agreement'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'Disputes over the inheritance caused discord in the family.' },
  { word: 'consensus', pos: 'noun', level: 3, group: 'relations', avoid: ['consent'], meaning: 'general agreement among a group', opposite: 'general disagreement among a group', synonyms: ['agreement', 'unanimity'], antonyms: ['disagreement', 'dissent'], distractors: ['tariff', 'mosaic', 'lullaby', 'pilgrimage'], sentence: 'After hours of debate, the committee reached a consensus.' },
  { word: 'chaos', pos: 'noun', level: 1, group: 'relations', meaning: 'complete disorder and confusion', opposite: 'a state of neat and calm arrangement', synonyms: ['disorder', 'turmoil'], antonyms: ['order', 'calm'], distractors: ['ladder', 'journey', 'blanket', 'kettle'], sentence: 'The power cut caused chaos at the airport.' },
  { word: 'tranquillity', pos: 'noun', level: 2, group: 'relations', avoid: ['anxiety'], meaning: 'the state of being calm and peaceful', opposite: 'the state of being noisy and disturbed', synonyms: ['calm', 'serenity'], antonyms: ['turmoil', 'agitation'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'We enjoyed the tranquillity of the mountain village.' },
  { word: 'affection', pos: 'noun', level: 1, group: 'relations', meaning: 'a feeling of fondness or liking', opposite: 'a feeling of strong dislike', synonyms: ['fondness', 'love'], antonyms: ['dislike', 'hatred'], distractors: ['ladder', 'blanket', 'kettle', 'umbrella'], sentence: 'The old man spoke of his village with great affection.' },
  { word: 'cruelty', pos: 'noun', level: 1, group: 'relations', meaning: 'behaviour that deliberately causes pain to others', opposite: 'behaviour that shows care for others', synonyms: ['brutality', 'savagery'], antonyms: ['kindness', 'compassion'], distractors: ['ladder', 'journey', 'blanket', 'kettle'], sentence: 'The law punishes cruelty to animals.' },
  { word: 'compassion', pos: 'noun', level: 2, group: 'relations', meaning: 'sympathy and concern for the suffering of others', opposite: 'a lack of concern for the suffering of others', synonyms: ['sympathy', 'pity'], antonyms: ['indifference', 'cruelty'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'The nurse treated every patient with compassion.' },
  { word: 'clemency', pos: 'noun', level: 3, group: 'relations', avoid: ['penalty'], meaning: 'mercy shown to an offender', opposite: 'harshness shown to an offender', synonyms: ['mercy', 'leniency'], antonyms: ['severity', 'harshness'], distractors: ['tariff', 'mosaic', 'lullaby', 'pilgrimage'], sentence: 'The judge showed clemency to the young offender.' },
  { word: 'ally', pos: 'noun', level: 1, group: 'relations', meaning: 'a person or country that supports another', opposite: 'a person or country that fights another', synonyms: ['partner', 'supporter'], antonyms: ['enemy', 'opponent'], distractors: ['tenant', 'sculptor', 'merchant', 'pilgrim'], sentence: 'The small country looked for an ally to help defend its borders.' },
  { word: 'adversary', pos: 'noun', level: 2, group: 'relations', meaning: 'an opponent in a contest or conflict', opposite: 'a supporter in a contest or conflict', synonyms: ['opponent', 'enemy'], antonyms: ['ally', 'friend'], distractors: ['tenant', 'sculptor', 'merchant', 'pilgrim'], sentence: 'The chess champion shook hands with his adversary.' },

  // ------------------------------------------------------------------ nouns: wealth
  { word: 'poverty', pos: 'noun', level: 1, group: 'quantity', meaning: 'the state of being extremely poor', opposite: 'the state of being very rich', synonyms: ['penury', 'destitution'], antonyms: ['wealth', 'affluence'], distractors: ['ladder', 'journey', 'blanket', 'umbrella'], sentence: 'Millions of people still live in poverty.' },
  { word: 'affluence', pos: 'noun', level: 3, group: 'quantity', meaning: 'the state of having a great deal of money', opposite: 'the state of having very little money', synonyms: ['wealth', 'riches'], antonyms: ['poverty', 'penury'], distractors: ['lullaby', 'mosaic', 'sonnet', 'pilgrimage'], sentence: "The suburb's affluence is obvious from its large houses." },
  { word: 'prosperity', pos: 'noun', level: 2, group: 'quantity', avoid: ['victory'], meaning: 'the state of being successful, especially financially', opposite: 'the state of suffering financial hardship', synonyms: ['affluence', 'wealth'], antonyms: ['poverty', 'adversity'], distractors: ['ceremony', 'souvenir', 'pendulum', 'carnival'], sentence: 'Peace brought a long period of prosperity to the region.' },
  { word: 'extravagance', pos: 'noun', level: 2, group: 'quantity', meaning: 'excessive or wasteful spending', opposite: 'careful and sparing spending', synonyms: ['wastefulness', 'lavishness'], antonyms: ['thrift', 'economy'], distractors: ['ceremony', 'pendulum', 'orchard', 'souvenir'], sentence: "The king's extravagance emptied the royal treasury." },

  // ------------------------------------------------------------------ nouns: mood
  { word: 'despair', pos: 'noun', level: 2, group: 'mood', meaning: 'the complete loss of hope', opposite: 'a strong feeling of hope', synonyms: ['hopelessness', 'despondency'], antonyms: ['hope', 'optimism'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'The farmers looked at the flooded fields in despair.' },
  { word: 'optimism', pos: 'noun', level: 1, group: 'mood', meaning: 'hopefulness about the future', opposite: 'a gloomy view of the future', synonyms: ['hopefulness', 'hope'], antonyms: ['pessimism', 'despair'], distractors: ['ladder', 'journey', 'blanket', 'kettle'], sentence: 'Her optimism kept the team going through difficult times.' },
  { word: 'sorrow', pos: 'noun', level: 1, group: 'mood', avoid: ['compassion'], meaning: 'a feeling of deep sadness', opposite: 'a feeling of great happiness', synonyms: ['grief', 'sadness'], antonyms: ['joy', 'happiness'], distractors: ['ladder', 'blanket', 'kettle', 'umbrella'], sentence: "The whole town shared the family's sorrow." },
  { word: 'jubilation', pos: 'noun', level: 3, group: 'mood', avoid: ['victory'], meaning: 'a feeling of great joy and triumph', opposite: 'a feeling of deep sadness and defeat', synonyms: ['elation', 'exultation'], antonyms: ['sorrow', 'despondency'], distractors: ['tariff', 'mosaic', 'almanac', 'pilgrimage'], sentence: 'There was jubilation in the streets when the team won the cup.' },
  { word: 'melancholy', pos: 'noun', level: 2, group: 'mood', meaning: 'a deep and long-lasting sadness', opposite: 'a lasting cheerfulness', synonyms: ['sadness', 'gloom'], antonyms: ['cheerfulness', 'joy'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'A mood of melancholy hung over the deserted village.' },
  { word: 'anxiety', pos: 'noun', level: 1, group: 'mood', meaning: 'a feeling of worry or unease', opposite: 'a feeling of calm and ease', synonyms: ['worry', 'unease'], antonyms: ['calmness', 'composure'], distractors: ['ladder', 'blanket', 'kettle', 'umbrella'], sentence: 'Waiting for the results filled him with anxiety.' },
  { word: 'apathy', pos: 'noun', level: 3, group: 'mood', meaning: 'a lack of interest or concern', opposite: 'a strong interest and concern', synonyms: ['indifference', 'unconcern'], antonyms: ['enthusiasm', 'passion'], distractors: ['tariff', 'mosaic', 'lullaby', 'almanac'], sentence: 'Voter apathy led to a very low turnout.' },
  { word: 'zeal', pos: 'noun', level: 2, group: 'mood', meaning: 'great energy and enthusiasm for a cause', opposite: 'a lack of energy or enthusiasm for a cause', synonyms: ['enthusiasm', 'passion'], antonyms: ['apathy', 'indifference'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'She campaigned for clean water with tireless zeal.' },

  // ------------------------------------------------------------------ nouns: energy
  { word: 'vigour', pos: 'noun', level: 2, group: 'mood', avoid: ['flaw'], meaning: 'physical strength and energy', opposite: 'physical weakness and tiredness', synonyms: ['energy', 'vitality'], antonyms: ['weakness', 'lethargy'], distractors: ['ceremony', 'souvenir', 'orchard', 'carnival'], sentence: 'At eighty, he still walks with remarkable vigour.' },
  { word: 'lethargy', pos: 'noun', level: 3, group: 'mood', meaning: 'a lack of energy and enthusiasm', opposite: 'an abundance of energy and enthusiasm', synonyms: ['sluggishness', 'inertia'], antonyms: ['vigour', 'energy'], distractors: ['tariff', 'mosaic', 'almanac', 'pilgrimage'], sentence: 'The afternoon heat filled the whole class with lethargy.' },
  { word: 'fatigue', pos: 'noun', level: 1, group: 'mood', meaning: 'extreme tiredness', opposite: 'a fresh and rested state', synonyms: ['tiredness', 'exhaustion'], antonyms: ['energy', 'freshness'], distractors: ['ladder', 'journey', 'kettle', 'umbrella'], sentence: 'After the long march, the soldiers were overcome by fatigue.' },

  // ------------------------------------------------------------------ nouns: words and ideas
  { word: 'brevity', pos: 'noun', level: 2, group: 'ideas', avoid: ['dearth', 'scarcity', 'plethora', 'surplus', 'abundance'], meaning: 'the use of few words; conciseness', opposite: 'the use of too many words', synonyms: ['conciseness', 'succinctness'], antonyms: ['verbosity', 'wordiness'], distractors: ['ceremony', 'souvenir', 'orchard', 'carnival'], sentence: 'Newspaper editors value brevity in a headline.' },
  { word: 'verbosity', pos: 'noun', level: 3, group: 'ideas', avoid: ['plethora', 'surplus'], meaning: 'the use of more words than needed', opposite: 'the use of only as many words as needed', synonyms: ['wordiness', 'prolixity'], antonyms: ['brevity', 'conciseness'], distractors: ['tariff', 'lullaby', 'almanac', 'pilgrimage'], sentence: 'The examiners criticised the essay for its verbosity.' },
  { word: 'fallacy', pos: 'noun', level: 3, group: 'ideas', avoid: ['deceit', 'honesty', 'candour'], meaning: 'a mistaken belief', opposite: 'a belief that is correct', synonyms: ['misconception', 'error'], antonyms: ['truth', 'fact'], distractors: ['tariff', 'lullaby', 'sonnet', 'pilgrimage'], sentence: 'It is a fallacy that money always brings happiness.' },
  { word: 'wisdom', pos: 'noun', level: 1, group: 'ideas', meaning: 'good judgement based on knowledge and experience', opposite: 'a lack of good judgement', synonyms: ['sagacity', 'insight'], antonyms: ['folly', 'foolishness'], distractors: ['ladder', 'blanket', 'kettle', 'umbrella'], sentence: "Grandmother's wisdom guided the family through hard times." },
  { word: 'folly', pos: 'noun', level: 2, group: 'ideas', meaning: 'a lack of good sense', opposite: 'the possession of good sense', synonyms: ['foolishness', 'stupidity'], antonyms: ['wisdom', 'prudence'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'It would be folly to swim in such rough seas.' },
  { word: 'expertise', pos: 'noun', level: 2, group: 'ideas', meaning: 'expert skill or knowledge', opposite: 'a lack of skill or knowledge', synonyms: ['skill', 'proficiency'], antonyms: ['incompetence', 'ineptitude'], distractors: ['ceremony', 'souvenir', 'orchard', 'carnival'], sentence: 'The project needs the expertise of a structural engineer.' },
  { word: 'novice', pos: 'noun', level: 2, group: 'ideas', meaning: 'a person who is new to an activity', opposite: 'a person with long experience of an activity', synonyms: ['beginner', 'learner'], antonyms: ['expert', 'veteran'], distractors: ['tenant', 'sculptor', 'merchant', 'pilgrim'], sentence: 'As a novice, he lost every game of his first chess tournament.' },
  { word: 'veteran', pos: 'noun', level: 2, group: 'ideas', meaning: 'a person with long experience in a field', opposite: 'a person with no experience in a field', synonyms: ['expert', 'old hand'], antonyms: ['novice', 'beginner'], distractors: ['tenant', 'sculptor', 'merchant', 'pilgrim'], sentence: 'She is a veteran of thirty years in journalism.' },
  { word: 'inception', pos: 'noun', level: 3, group: 'ideas', meaning: 'the start of an institution or activity', opposite: 'the close of an institution or activity', synonyms: ['beginning', 'outset'], antonyms: ['end', 'conclusion'], distractors: ['tariff', 'mosaic', 'lullaby', 'pilgrimage'], sentence: 'The society has grown steadily since its inception in 1990.' },

  // ------------------------------------------------------------------ nouns: fame and worth
  { word: 'renown', pos: 'noun', level: 2, group: 'ideas', meaning: 'the state of being famous and admired', opposite: 'the state of being unknown', synonyms: ['fame', 'eminence'], antonyms: ['obscurity', 'anonymity'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'The poet won renown for his ghazals.' },
  { word: 'obscurity', pos: 'noun', level: 3, group: 'ideas', meaning: 'the state of being unknown or forgotten', opposite: 'the state of being widely known', synonyms: ['anonymity', 'oblivion'], antonyms: ['fame', 'renown'], distractors: ['tariff', 'mosaic', 'lullaby', 'pilgrimage'], sentence: 'The singer died in obscurity, forgotten by her fans.' },
  { word: 'flaw', pos: 'noun', level: 1, group: 'ideas', meaning: 'a fault or weakness that spoils something', opposite: 'a quality that makes something better', synonyms: ['defect', 'fault'], antonyms: ['merit', 'strength'], distractors: ['ladder', 'blanket', 'kettle', 'journey'], sentence: 'The inspector found a flaw in the design of the bridge.' },
  { word: 'merit', pos: 'noun', level: 2, group: 'ideas', avoid: ['criticism', 'acclaim', 'eulogy', 'penalty'], meaning: 'the quality of deserving praise', opposite: 'the quality of deserving blame', synonyms: ['worth', 'excellence'], antonyms: ['demerit', 'fault'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: 'Scholarships are awarded on merit alone.' },
  { word: 'victory', pos: 'noun', level: 1, group: 'ideas', meaning: 'success in a contest or battle', opposite: 'failure in a contest or battle', synonyms: ['triumph', 'win'], antonyms: ['defeat', 'loss'], distractors: ['ladder', 'blanket', 'kettle', 'umbrella'], sentence: 'The captain dedicated the victory to his coach.' },

  // ------------------------------------------------------------------ nouns: help, rules, safety
  { word: 'obstacle', pos: 'noun', level: 1, group: 'rules', avoid: ['ally'], meaning: 'a thing that blocks the way or prevents progress', opposite: 'a thing that helps progress', synonyms: ['barrier', 'hindrance'], antonyms: ['aid', 'assistance'], distractors: ['ladder', 'blanket', 'kettle', 'umbrella'], sentence: 'Lack of money was the biggest obstacle to her studies.' },
  { word: 'impediment', pos: 'noun', level: 3, group: 'rules', avoid: ['ally'], meaning: 'something that hinders or obstructs', opposite: 'something that makes progress easier', synonyms: ['obstacle', 'hindrance'], antonyms: ['aid', 'assistance'], distractors: ['almanac', 'mosaic', 'lullaby', 'sonnet'], sentence: 'Poor roads are an impediment to trade between the villages.' },
  { word: 'consent', pos: 'noun', level: 2, group: 'rules', meaning: 'permission for something to happen', opposite: 'a refusal to allow something', synonyms: ['permission', 'approval'], antonyms: ['refusal', 'prohibition'], distractors: ['ceremony', 'souvenir', 'orchard', 'pendulum'], sentence: "No photograph may be published without the owner's consent." },
  { word: 'penalty', pos: 'noun', level: 1, group: 'rules', meaning: 'a punishment for breaking a rule or law', opposite: 'something given in return for good conduct', synonyms: ['punishment'], antonyms: ['reward'], distractors: ['ladder', 'blanket', 'kettle', 'journey'], sentence: 'There is a heavy penalty for parking on the pavement.' },
  { word: 'peril', pos: 'noun', level: 2, group: 'rules', avoid: ['tranquillity', 'harmony'], meaning: 'serious and immediate danger', opposite: 'freedom from danger', synonyms: ['danger', 'jeopardy'], antonyms: ['safety', 'security'], distractors: ['ceremony', 'souvenir', 'orchard', 'carnival'], sentence: 'The fishermen were in great peril during the storm.' },
];
